export const guidToName = {
    "060a48f0-117b-4b22-a165-111fd4a5b745": "Ambrose Island",
    "76fd7c40-83a0-48c9-be49-cef107583eae": "Hokkaido",
    "ebb8cdab-e521-4ba8-9288-d697b1aaaba7": "Paris",
    "d40076af-74d1-484e-8936-1367d5b107ce": "Bangkok",
    "107100ca-f910-49a9-ac13-59d0bb5691a4": "Colombia",
    "1a98c48e-d618-4d4d-b17b-90ca3b180d2a": "Colorado",
    "d4719601-83ce-4ca9-83cd-5164331d643f": "Sapienza",
    "d84fb174-2cbb-4337-8a66-f13f9fb170cd": "Dartmoor",
    "0ffe44ea-d241-49ec-835c-74d5714db343": "Berlin",
    "f075fbc3-79ef-4e42-9326-9572f712a298": "Haven Island",
    "59c15d1e-c65e-4394-9906-46cdeb944c64": "Mumbai",
    "4d9b38ab-5ea8-4bc3-8fbe-273a36c72731": "Chongqing",
    "dac2d6fd-4f25-4a63-b338-aef458c05a7f": "Whittleton Creek",
    "4a34f12a-ab98-4dc5-9262-c600193b2629": "Miami",
    "37be638c-4265-4622-9326-8835b8535180": "Isle of Sgàil",
    "3e72588a-46ea-4cb8-a10f-e2242ca8cc99": "Ambrose Island (Showdown)",
    "65659b19-fb1a-4a14-b074-65227ffac128": "Hokkaido (Showdown)",
    "c945b720-12c4-4f62-8026-4b4011a67dff": "Paris (Showdown)",
    "2f562dba-2b14-42f3-b9fb-eb72e79450ba": "Bangkok (Showdown)",
    "aab7a569-cead-40b8-81b5-c1605070b366": "Colombia (Showdown)",
    "4a95baa5-6ad6-43c8-ae3e-be8449d578ec": "Colorado (Showdown)",
    "47d10233-0008-4f34-abd2-a84ca2bb7530": "Sapienza (Showdown)",
    "dec0ed42-41bf-4ff0-bc0a-08d73b3e7430": "Dartmoor (Showdown)",
    "c147e93f-2fa6-4618-a84e-d929c5d3d391": "Berlin (Showdown)",
    "d2419fe4-ea72-4e61-b91b-bb39706f551d": "Haven Island (Showdown)",
    "0d2a243a-f140-4be5-bfe7-e151878ec88e": "Mumbai (Showdown)",
    "5162c4a1-4b07-43b1-82ad-37c9e350764c": "Chongqing (Showdown)",
    "6efd360a-5f78-44ac-9823-df077018c2b3": "Whittleton Creek (Showdown)",
    "ee67660e-4bd6-4743-9163-40331056f690": "Miami (Showdown)",
    "aa6447f6-7566-4e54-b1c9-15fa3d4acb39": "Isle of Sgàil (Showdown)"
};

export const brickToName = {
    "assembly:/_pro/scenes/missions/rocky/tod_midday.brick": "Day",
    "assembly:/_pro/scenes/missions/rocky/tod_sunset.brick": "Sunset",
    "assembly:/_pro/scenes/missions/rocky/override_poker.brick": "Vanilla",
    "assembly:/_pro/scenes/missions/hokkaido/mission_mild_flu.brick": "Patient Zero",
    "assembly:/_pro/scenes/missions/hokkaido/mission_hot_flu.brick": "Patient Zero",
    "assembly:/_pro/scenes/missions/hokkaido/mission_mild_mamushi.brick": "Snow Festival",
    "assembly:/_pro/scenes/missions/hokkaido/hsf_night.brick": "Snow Festival",
    "assembly:/_pro/scenes/missions/hokkaido/tod_flu.brick": "Day",
    "assembly:/_pro/scenes/missions/hokkaido/override_shogi.brick": "Vanilla",
    "assembly:/_pro/scenes/missions/paris/location_parisnoel.brick": "Christmas",
    "assembly:/_pro/scenes/missions/paris/gamechangers_wild_card_juniper.brick": "Vanilla",
    "assembly:/_pro/scenes/missions/paris/tod_midday.brick": "Day",
    "assembly:/_pro/scenes/missions/paris/tod_ets_mild.brick": "UNKNOWN",
    "assembly:/_pro/scenes/missions/paris/tod_ets.brick": "UNKNOWN",
    "assembly:/_pro/scenes/missions/bangkok/mission_mild_zika.brick": "UNKNOWN",
    "assembly:/_pro/scenes/missions/bangkok/override_constantjeff.brick": "UNKNOWN",
    "assembly:/_pro/scenes/missions/bangkok/gamechanger_wild_card_geranium.brick": "Vanilla",
    "assembly:/_pro/scenes/missions/bangkok/tod_zika_night.brick": "Night",
    "assembly:/_pro/scenes/missions/bangkok/tod_warlord_midday.brick": "Day",
    "assembly:/_pro/scenes/missions/bangkok/tod_warlord_hot_midday.brick": "Day",
    "assembly:/_pro/scenes/missions/colombia/mission_mild_anaconda.brick": "UNKNOWN",
    "assembly:/_pro/scenes/missions/colombia/mission_hot_anaconda.brick": "UNKNOWN",
    "assembly:/_pro/scenes/missions/colombia/gamechanger_hippo_zinnia.brick": "UNKNOWN",
    "assembly:/_pro/scenes/missions/colombia/gamechanger_hippo_holly.brick": "UNKNOWN",
    "assembly:/_pro/scenes/missions/colorado_2/ets_night.brick": "Night",
    "assembly:/_pro/scenes/missions/colorado_2/ets_night_mild.brick": "Night",
    "assembly:/_pro/scenes/missions/colorado_2/scenario_rabies_spades.brick": "Patient Zero",
    "assembly:/_pro/scenes/missions/colorado_2/mission_mild_rabies.brick": "Patient Zero",
    "assembly:/_pro/scenes/missions/colorado_2/gamechanger_wild_card_daisy.brick": "Vanilla",
    "assembly:/_pro/scenes/missions/colorado_2/lighting_day.brick": "Day",
    "assembly:/_pro/scenes/missions/coastaltown/tod_ets_sunset.brick": "Sunset",
    "assembly:/_pro/scenes/missions/coastaltown/tod_mild_sunset.brick": "Sunset",
    "assembly:/_pro/scenes/missions/coastaltown/tod_ebola_night.brick": "Night",
    "assembly:/_pro/scenes/missions/coastaltown/gamechanger_wild card_jasmine.brick": "Vanilla",
    "assembly:/_pro/scenes/missions/ancestral/tod_midday.brick": "Day",
    "assembly:/_pro/scenes/missions/ancestral/override_bridge.brick": "Vanilla",
    "assembly:/_pro/scenes/missions/ancestral/mission_mild_dgs.brick": "Garden Show (Day)",
    "assembly:/_pro/scenes/missions/edgy/mission_fox/tod_et_midday.brick": "Day",
    "assembly:/_pro/scenes/missions/edgy/mission_fox/tod_sunset.brick": "Sunset",
    "assembly:/_pro/scenes/missions/edgy/mission_fox/override_meyer.brick": "Vanilla",
    "assembly:/_pro/scenes/missions/opulent/mission_stingray/tod_night.brick": "Night",
    "assembly:/_pro/scenes/missions/opulent/mission_stingray/override_hilo.brick": "Vanilla",
    "assembly:/_pro/scenes/missions/mumbai/tod_night.brick": "Night",
    "assembly:/_pro/scenes/missions/mumbai/tod_midday.brick": "Day",
    "assembly:/_pro/scenes/missions/mumbai/gamechanger_monkshood_holyman_override.brick": "Vanilla",
    "assembly:/_pro/scenes/missions/wet/tod_redsnapper_cloudy.brick": "Cloudy?",
    "assembly:/_pro/scenes/missions/wet/tod_midday.brick": "Day",
    "assembly:/_pro/scenes/missions/wet/mission_mild_mahjong.brick": "Vanilla",
    "assembly:/_pro/scenes/missions/skunk/tod_elusive_night.brick": "Night",
    "assembly:/_pro/scenes/missions/skunk/override_solitaire.brick": "Vanilla",
    "assembly:/_pro/scenes/missions/miami/tod_night_ass.brick": "Night",
    "assembly:/_pro/scenes/missions/miami/override_pinochle.brick": "Vanilla",
    "assembly:/_pro/scenes/missions/theark/tod_day_ets_mild.brick": "Day",
    "assembly:/_pro/scenes/missions/theark/tod_day_ets.brick": "Day",
    "assembly:/_pro/scenes/missions/theark/gamechanger_magpie_locked_jail_door.brick": "Vanilla"
};